### ISSUE TITLE
Another fuzzed assertion (foster_parent_element: Assertion `open_elements->length > 2')

### ISSUE THREAD

**Issue by gsnedders** [google/gumbo-parser#279]
This is from the following:

    <math><th><mI><table></table><tr></table><div><tr>0

Resulting in:

    get_title: src/parser.c:765: foster_parent_element: Assertion `open_elements->length > 2' failed.

I'm not sure quite what's going on here. Something is going wrong, and fairly early on I think. The stack of open elements ends up with just `html` and `tr` on it. Could easily be a bug similar to #278 leading to over-popping from the stack.

**Comment by aroben** [comment]
Here's the sequence of events according to the debugger and the spec:

* `</table>` token is processed. Insertion mode is changed to "in cell" because of the open `th` element.
* `<tr>` token is processed in "in cell" insertion mode. This performs the [close the cell](https://html.spec.whatwg.org/multipage/syntax.html#close-the-cell) steps, which pops everything up to and including the `th` off the stack and changes the insertion mode to "in row". At this point the stack of open elements consists of `html`, `body`, `math`.
* `<tr>` token is reprocessed as foreign content (because the current node is `math`) and inserted.

At this point Gumbo's behavior has diverged from Safari, Chrome, and Firefox. According to [Live DOM Viewer](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cmath%3E%3Cth%3E%3CmI%3E%3Ctable%3E%3C%2Ftable%3E%3Ctr%3E%3C%2Ftable%3E%3Cdiv%3E%3Ctr%3E0), the browsers do not insert a `tr` element here.

Continuing on:

* `</table> is processed in "in row" insertion mode (still set from before). Pops the `tr` from the stack and insertion mode is set to "in table body".
* `</table>` is reprocessed as foreign content (because `math` is now the current node). This falls into the "any other end tag" case, which tells us to process it according to the current insertion mode.
* `</table>` is processed in "in table body" insertion mode and ignored.
* `<div>` is processed as foreign content (because `math` is still the current node). This pops off the `math` element.
* `<div>` is reprocessed in "in table body" insertion mode (still set from above), which falls through to "in table" insertion mode, which falls through to "in body" with foster parenting enabled, which inserts a `div`.
* `<tr>` is processed in "in table body" insertion mode (still set from above). This [clears the stack back to a table body context](https://html.spec.whatwg.org/multipage/syntax.html#clear-the-stack-back-to-a-table-body-context), which pops off everything but the `html` node.

The spec says that we should only get back to the `html` node when parsing fragments. But we aren't parsing a fragment here.

@hixie This seems like a spec bug since we're hitting a "fragment case" when not parsing a fragment. Maybe the spec should be changed to match whatever browsers are doing when they hit that first `<tr>` tag?

**Comment by gsnedders** [comment]
It's been believed for a long while that the "fragment case" annotations aren't accurate, FWIW.

**Comment by gsnedders** [comment]
Looking closely, you've made the common mistake with reading the spec (suggestions for how to fix this would undoubtedly be appreciated!). Note from the "Parsing HTML Documents" introduction:

> As stated in the terminology section, references to element types that do not explicitly specify a namespace always refer to elements in the HTML namespace. For example, if the spec talks about "a `menuitem` element", then that is an element with the local name "`menuitem", the namespace "`http://www.w3.org/1999/xhtml`", and the interface `HTMLMenuItemElement`. Where possible, references to such elements are hyperlinked to their definition.

Also look at the "tree construction dispatcher", which I think you've also missed (in the "tree construction" section).

Let me try and follow this through per spec (not looking at Gumbo in a debugger though — I trust what you've said there is right):

 * `<table>` (stack is currently `html:html`, `html:body`, `math:math`, `math:th`, `math:mi`): the adjusted current node is a MathML text integration point and the token is a start tag whose tag name is neither "`mglyph`" nor "`malignmark`", so we parse using the current insertion mode ("in body"). This inserts a `html:table` element and changes the insertion mode to the "in table" insertion mode.

 * (first) `</table>` (stack is currently `html:html`, `html:body`, `math:math`, `math:th`, `math:mi`, `html:table`): we have a `table` element in table scope, so we pop elements till we've popped `html:table` (i.e., we pop a single item). We then reset the insertion mode, and we walk up the stack till we hit `html:body` (we *do not* match the `math:th` element because of the above quote — when the spec says "a `th` element" it means one in the HTML namespace) when we finally match something and reset it to "in body".

* (first) `<tr>` (stack is everything up to `math:mi`): the adjusted current node is a MathML text integration point so we parse using the current insertion mode ("in body"). This is a parse error, we ignore the token.

* (second) `</table>` (stack is same as previous step): still "in body", so this falls to the "any other end tag" case, which then falls from the "Otherwise, if node is in the special category, then this is a parse error; ignore the token, and abort these steps" step having changed nothing.

* `<div>` (stack is still the same): gets inserted as an ordinary element and added to the stack, insertion mode remains in body.

* (second) `<tr>` (stack is same but with `html:div` on the end): this is again a parse error and ignored.

Therefore, the behaviour in all browsers is correct per spec, and this very closely related to #278 (i.e., this is just because we're treating a `math:th` element as if it were `html:th`).

**Comment by gsnedders** [comment]
(I'm closing this because it's essentially #278 just manifesting itself in another place.)

**Comment by aroben** [comment]
I did indeed miss the paragraph you quoted about defaulting to the HTML namespace. I also missed this phrase from the "any other start tag" section when parsing tags in foreign content:

> Insert a foreign element for the token, **in the same namespace as the adjusted current node**.

I think your analysis is correct. Thanks!
