### ISSUE TITLE
bug in v1.0 (and others?) regarding handling of rtc tags

### ISSUE THREAD

**Issue by kevinhendricks** [google/gumbo-parser#300]
Update:  This bug exists in master, v1.0.0 and v0.10.0:

Somehow during the merging, a part of the code that handles the ruby related tags got messed up from what we had in vmg's tree, this is what causes the ruby related parser failure in v1.0.0

In addition, I still can not find anything in the nightly W3C HTML5.1 spec that refers to anything related to  "generate_all_implied_end_tags_thoroughly" as opposed to the normal generate_implied end tags.
That said the normal version of "generate_implied end tags" includes RB which the "thoroughly" version does not (therefore hunk 1 in the patch) which would make it not "thorough"!  

Either way, isn't the latest Editor version of the HTML5.1 spec from the W3c the proper target for the v1.0.0 tree:  

http://www.w3.org/html/wg/drafts/html/master/syntax.html#syntax

This is the most recent version of the spec I believe.  If I am wrong someone, please let me know.

The second hunk is actually what fixes the the html5libtest.  The condition got the exceptions reversed when you compare it to the original in vmg and the official spec and was incomplete as well.  In other words, when the tag is RT then the exception is GUMBO_TAG_RTC;  And if the tag is in { RB, RP, RTC) , there is no exception so it should be GUMBO_TAG_LAST. 

Here is the patch that fixes this.  With this patch in place in v1.0.0, we have just 3 remaining failures all related to foreign templates in the master version of html5lib_tests-master.

```
--- src/parser.c.orig	2015-02-18 11:53:46.000000000 -0500
+++ src/parser.c	2015-02-18 12:15:53.000000000 -0500
@@ -1515,7 +1515,7 @@
   for (;
        node_tag_in_set(get_current_node(parser), (gumbo_tagset) { TAG(CAPTION),
              TAG(COLGROUP), TAG(DD), TAG(DT), TAG(LI), TAG(OPTION), TAG(OPTGROUP),
-             TAG(P), TAG(RP), TAG(RT), TAG(RTC), TAG(TBODY), TAG(TD),
+             TAG(P), TAG(RP), TAG(RB), TAG(RT), TAG(RTC), TAG(TBODY), TAG(TD),
              TAG(TFOOT), TAG(TH), TAG(HEAD), TAG(TR) });
        pop_current_node(parser));
 }
@@ -2945,8 +2945,7 @@
   } else if (tag_in(token, kStartTag, (gumbo_tagset) {
         TAG(RB), TAG(RP), TAG(RT), TAG(RTC) })) {
     bool success = true;
-    GumboTag exception = tag_in(token, kStartTag, (gumbo_tagset) {
-        TAG(RT), TAG(RP) }) ? GUMBO_TAG_RTC : GUMBO_TAG_LAST;
+    GumboTag exception = tag_is(token, kStartTag, GUMBO_TAG_RT) ? GUMBO_TAG_RTC : GUMBO_TAG_LAST;
     if (has_an_element_in_scope(parser, GUMBO_TAG_RUBY)) {
       generate_implied_end_tags(parser, exception);
     }

```

**Comment by nostrademons** [comment]
We work off the [WhatWG spec](https://html.spec.whatwg.org/multipage/) for the most part, because that tracks what browsers actually have implemented.  The W3C spec tends to lag often.  The exception is the \<ruby> tag handling, which was a W3C addition that has been implemented cross-browser but just hasn't yet made it into the WhatWG version.  More generally, when there are differences between test behavior and WhatWG spec they should be raised as bugs on html5lib-tests.

There's some discussion on this in [html5lib issue 51](https://github.com/html5lib/html5lib-tests/issues/51), where a W3C member replied and basically gave the above explanation.  This specific bug was raised in [html5lib issue 54](https://github.com/html5lib/html5lib-tests/issues/54) and acknowledged as a bug in the test suite; I've got a patch out in [html5lib pull request 55](https://github.com/html5lib/html5lib-tests/pull/55).

(Yes, this spec fork sucks for implementors.  I've cursed it out many times before.  For Gumbo, I've just tried to follow what major browsers do, which is generally captured in the html5lib test suite.)

**Comment by kevinhendricks** [comment]
Then I have been using the wrong spec.  Based on your links Gumbo uses WhatWG even though it lags the official spec as its target (or sometimes leads it)?  Sorry, I thought the  right target for 1.0.0 would be the official W3C Nightly or Editor HTML 5.1 syntax spec.  Please close this issue.

I sincerely hope there are not too many deviations between the two versions of the spec.    I will revert that patch in my local trees and update to the now fixed html5lib tests master.

**Comment by kevinhendricks** [comment]
not a bug but a feature so closing
