### ISSUE TITLE
feature request for better way to get correct tag name

### ISSUE THREAD

**Issue by kevinhendricks** [google/gumbo-parser#305]
Please consider what we have to go through now to get to the real tag name for all cases that is properly cased   (code below is c++)

```
static std::string get_tag_name(GumboNode *node)
{
  std::string tagname;
  if (node->type == GUMBO_NODE_DOCUMENT) {
    tagname = "document";
    return tagname;
  }
  tagname = gumbo_normalized_tagname(node->v.element.tag);
  if ((tagname.empty()) ||
      (node->v.element.tag_namespace == GUMBO_NAMESPACE_SVG)) {

    // set up to examine original text of tag                                                                                   
    GumboStringPiece gsp = node->v.element.original_tag;
    gumbo_tag_from_original_text(&gsp);

    // special handling for some svg tag names                                                                                  
    if (node->v.element.tag_namespace  == GUMBO_NAMESPACE_SVG) {
      const char * data = gumbo_normalize_svg_tagname(&gsp);
      // NOTE: data may not be null-terminated!                                                                                 
      // since case change only - length must be same as original.
      // returns null not original string if no replacement                                                      
      if (data != NULL) {
        return std::string(data, gsp.length);
      }
    }
    if (tagname.empty()) {
      return std::string(gsp.data, gsp.length);
    }
  }
  return tagname;
}
```

Perhaps we should add a new interface that expands on  gumbo_normalized_tagname to handle all of the above automagically?  I see the gumboc.py going through the same long path just to get a proper tag name.  It would seem to be a common enough request that gumbo should handle all of this for the user with one call.

**Comment by nostrademons** [comment]
Yeah, this is pretty gross.  The main reason for it is, again, memory-management.  For known tags, the tagname is static data, so it can't be freed.  For unknown tags, the options are to return a portion of original_text as a GumboStringPiece (which is what gumbo_tag_from_original_text does) or to allocate a buffer, which must be freed by the calling code.  I didn't want to allocate because it meant the caller (which might not even be written in the same language, since there are so many language bindings) would have to deallocate, which at present requires the original GumboOptions.  Also, these two different functions have different type signatures - the reason for that is because a const char* is *much* easier for a C library that needs to interoperate with other C libraries to deal with, and so making everything work in terms of GumboStringPieces would be even more of a pain.

In some ways, it's debatable whether the function is even correct, since HTML is case-insensitive and yet the original_tagname codepath will put the case-sensitive version of the tag into the StringPiece.

In my perfect world, this would be a function that takes a GumboNode* and returns a zero-terminated const char* that is freed automatically when gumbo_destroy_output is called.  I think that's possible with arenas, although it'd require a way to identify the arena that a node lives in to avoid having to pass the GumboArena into the function (which I could do by having a back-pointer from the GumboDocument, since that's the ultimate ancestor of all nodes in the document; it'd be ugly speed-wise though).
