### ISSUE TITLE
utf8.c - inline keyword not supported in C mode in Visual Studio

### ISSUE THREAD

**Issue by lowjoel** [google/gumbo-parser#320]
Hi there!

In e52b19bc978b7c753bff863fa6d222b1e439b916 an `inline` method was added to a C file. Visual C++ does not support this (only the __inline keyword in C; inline is supported in C++ mode); could it be removed or `#defined` out?

**Comment by mYmNeo** [comment]
You should have a look at http://stackoverflow.com/questions/2765164/inline-vs-inline-vs-inline-vs-forceinline. I think your compiler doesn't support C99.

**Comment by lowjoel** [comment]
I think we all know that VC++ doesn't support the full C99 specification. The question is, if gumbo is supposed to support VC++, then this should be properly handled.

**Comment by nostrademons** [comment]
Gumbo aims for "best effort" support for VC++; all Visual Studio support is contributed by volunteers (well, we're all volunteers here, but individual users of the library) who needed it for their projects.  I don't personally have a Windows machine available to me to test, and TravisCI doesn't support Windows, so regressions do occasionally creep in.  I agree that the solution here is to remove the inline keyword; in my experience, compilers will inline small methods like this regardless of the keyword (the commit in question pulled in some third-party code that was probably written before this could be relied upon).  I'll happily accept pull requests for this and any other VC++ cleanups; otherwise, I can remove the offending keyword next time I'm working with the code.

**Comment by lowjoel** [comment]
@nostrademons if the project wants to continue VC++ support, then I'll happily contribute a PR.

Yes, Travis doesn't support VC++, but AppVeyor does. If the team wants it, I could set up an appveyor.yml PR as well.

**Comment by nostrademons** [comment]
Yep, I'll take PRs, for both this and for AppVeyor (as long as its free and won't require additional maintainence).  I'm going to run the benchmarks against it as well; a small (1-2%) slowdown won't prevent it from being merged, but it is performance-critical code and I want to make sure my intuition about it being inlined anyway holds (or know what the effect is if it doesn't).

**Comment by lowjoel** [comment]
@nostrademons I'm intending to PR to #define inline __inline for VC++ using the command line args.

AppVeyor is free for open-source projects, and have a build time limit of 30 minutes (which should be plenty...)

**Comment by nostrademons** [comment]
SGTM.

**Comment by lowjoel** [comment]
Sorry, it appears that the particular issue was already solved in cfb473cf59. I'm working on adding AppVeyor, I'll submit a PR for that when I'm done.
