### ISSUE TITLE
Elements inside non elements should be parsed differently.

### ISSUE THREAD

**Issue by ytrezq** [google/gumbo-parser#346]
If an element is declared but not closed with`>`then the next`>`is parsed as the end of the element which wasn’t closed instead of the end of the element. Examples :
    `<p <div>some text</div>>other text</p>`
is parsed as :
    `<p some text>other text</p>`
because the`>`of`<div>`is parsed as the end of`p`instead of the end of`div`

```
<isindex prompt="some <div>text">
```

is parsed as
<isindex prompt="some <div>text">

**Comment by nostrademons** [comment]
The spec here says that the \< should start a new *attribute*, not a new element:

https://html.spec.whatwg.org/multipage/syntax.html#before-attribute-name-state

So the correct parse here is for the \< to add a new attribute with the name "<div".  When it reaches the next >, the current tag is emitted, even though it's unfinished, and "some text" is appended as the element's contents.  \</div> is parsed as a closing tag, which is ignored in tree construction because there's no \<div> open.  Then ">other text" is added as additional text in the \<p> node.

I think that's what you posted as the output you got, although HTML tags get eaten by markdown unless they're escaped by a backslash, so it's hard to see here.
