### ISSUE TITLE
How to take the HTML as plain text

### ISSUE THREAD

**Issue by guzur** [google/gumbo-parser#347]
Is there anyway to get the HTML after parsing it? I want to use the gumbo parser to fix the HTML and after that take the whole HTML. I saw that there is a example called prettyprint but it's build on C++ and I want to use only C. 

Is there any method to take the whole HTML or I have to build myself?

Thanks a lot.

**Comment by nostrademons** [comment]
There's no way that's built into the parser.  It's relatively easy to build such functionality yourself; after fixing the HTML, walk the tree and serialize it to a buffer, outputting HTML in the format that you desire.  The prettyprint and serialize examples (C++) are pretty close to this, and the rest of the examples all walk the tree in some way if you're looking for simpler C sample code.

**Comment by guzur** [comment]
Thank you Nostrademons for your answer, it looks like a little bit strange to don't have something as usefull as a printter of the HTML. 

Anyway thank you very much.

Cheers.

**Comment by nostrademons** [comment]
It's because output formats vary significantly depending on what you're using Gumbo for:

1. Are you sending HTML straight to a browser over the network, where it'll be interpreted just by machines?  Then you'll want to minify the HTML, omitting all whitespace, any end tags you can, any attribute quotes where possible, etc.
2. Are you sending HTML to a browser, but it has to be read by a human, eg. for debugging or development?  Then you'll want to pretty-print the HTML with whitespace and indentation.
3. Are you using Gumbo to cleanup existing code to a new company-wide standard, eg. making sure all attributes are quoted, all tags are lowercase, etc?  Then you want to output to the standard, which may vary in a number of details.
4. Are you generating HTML that needs to be post-processed by XML-based tools, as Sigil did (they contributed the serialize & pretty-print examples)?  Then you need to output XHTML.
5. Are you looking to build a generalized refactoring tool that works on source code, which'll be written back to your source repository?  Then, instead of serializing the whole tree, you may want to just mark the nodes that have changed as dirty, and use their offsets to serialize *only that part*, bringing over the unchanged parts verbatim from the original text.  This preserves the original author's formatting, which some developers are very picky about.

The easiest way to support all of these use-cases is to not favor any one of them by building it into the library; that keeps the API surface small and prevents the "Oh, it has this functionality, but it *almost* does what I want but not quite" problem.

**Comment by guzur** [comment]
Thanks for this extended answer Nostrademons, anyway it won't be better to have all that staff developed? Else everybody that needs any of that things will need to build their code and that will be a waste of time and work.

Anyway thank you for all this info and I will start developing my printer ;).

See you.
