### ISSUE TITLE
feature request: partial parse to get charset from <meta> tags.

### ISSUE THREAD

**Issue by okapia** [google/gumbo-parser#352]
it'd be useful to have a quick way to extract the charset from the header of an HTML file so that it can be put through iconv if needed. I can use a regular expression but given that gumbo can already do the parsing properly, it should be able to extract the charset more reliably. It would just need to be able to abort the parse early - either once the charset has been found or if it has gone far enough that it is reasonable to give up on find it. The charset can be in one or other of the following forms:
  <meta charset="utf-8"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

**Comment by nostrademons** [comment]
This has come up before in #68.  I view it as a reasonable request, given that Gumbo only supports UTF-8 and suggests that you use an external library to convert to UTF-8 if necessary.  The only major blocker was deciding what sort of API would be best for it:

1. Add a separate parseHead method.  Reasonably self-explanatory, but it feels like it'd bloat the API for people who don't want this functionality, and once an API method is added it's very hard to remove.
2. Add a flag on GumboOptions to stop after the head.  Easiest to implement.  Keeps the basic API simple while still allowing relatively easy usage when necessary.
3. Add a more general SAX-style callback mechanism that lets you stop at any point in the parse.  Most general, could be used for other stuff too (eg. finding only a known ID in the document), but may have a speed penalty, requires the most effort by client code, and is the most invasive in implementation.

Preferences?

My preference is probably for 2, but I might be convinced to go with 1.  I'd love to hear from 3rd-party language bindings: in Python at least, leaving a field out of the ctypes struct can result in crashes when it's part of another structure (since the memory layout doesn't match the C), and if this is the case in other language bindings as well, it's a good argument for adding a totally new method rather than a new struct field.  I used to be in favor of 3, but given that both feature requests have only been for the head and there's been a lot of work to speed up Gumbo in recent releases, it may be unnecessary generalization.

**Comment by okapia** [comment]
I don't have any strong preferences. Anything that facilitates the use case I mentioned would be great. Given the choice of 1 and 2, I'd probably favour 2 because, as you say, it keeps the basic API simple.
My concern with either would be whether gumbo would stumble over an input file with invalid UTF-8 in the `<head>`. Perhaps common in a `<title>`. Of course the charset *can* be anywhere within `<head>` but any smart programmer would ensure it appears early.
Thanks
