### ISSUE TITLE
serialize.cc license

### ISSUE THREAD

**Issue by TechnikEmpire** [google/gumbo-parser#354]
IANAL, but isn't there a conflict with the license declaration of `serialize.cc`? It claims to be based on code from BeautifulSoup 4, which is MIT, but it's listed under a different license without retaining or displaying copyright information from the authors of BeautifulSoup 4. Again I'm not a lawyer and for all I know there is no code shared between them. Just thought I'd raise the question because if there's no code shared, language like "based on" and referencing third party copyrighted material should probably be dropped.

**Comment by kevinhendricks** [comment]
I wrote it and it is based on the approach used in BS4 decode but is written in C++ and not python 2.7. So it has no actual code in common (two different languages) but certainly strives to do the same thing in the same way and to match what was done in bs4 to the extent possible.  Much of the code is unique to serialize.cc but I felt BS4 needed a nod.  I someone wants to add more than that nod, please do so

**Comment by TechnikEmpire** [comment]
@kevinhendricks Yeah I hate to be nitpicking, I appreciate your contribution it's helped me a great deal. I just want to make sure before I go copy it, put your license and release it that I'm complying properly all the way down the chain of copyright. All good, and yeah I realize they're two different languages but if I rewrite the lord of the rings in klingon, I still can't claim its my solely my IP and I'd have to maintain the license (if any) governing the original IP. Legal stuff sucks, not trying to be a downer.

**Comment by kevinhendricks** [comment]
Still have no idea about the license but if you want to add the MIT license to it, I am fine with that.   But since the node trees are different (have different node types), the code works differently, and except for names of variables (borrowed from the BS4 code to help me follow the logic) any approach to using recursion to serialize will have the same basic structure.  Again, you would need a lawyer to tell you (an one that understands code as well!).

BTW: In case you are interested, my gumbo tree in the usexhtml branch, has a more up to date version of serialize that uses deals with cdata and comments and the like.

**Comment by TechnikEmpire** [comment]
@kevinhendricks Thanks for the clarification and pointing to a newer version. haha so cool I JUST finished making my own version and I made a lot of the changes I see you made here, namely the unordered sets for lookups and stuff. Was able to boost the speed 2X over the version in the official master branch. Thanks again!
