### ISSUE TITLE
licensing?

### ISSUE THREAD

**Issue by Falven** [google/gumbo-parser#364]
There is no licensing information anywhere that I can see. Could this information be provided or made more apparent? Usually repositories provide a LICENSE.txt in their top level directory with relevant information.

**Comment by nostrademons** [comment]
It's in the COPYING file - Apache 2 license, like all Google open-source software (at least at the time that Gumbo was open-sourced; no idea if policies have changed since then).  The top of each source file has licensing info as well.

(I honestly don't remember why its COPYING instead of LICENSE.txt, since my personal preference would've been LICENSE as well.  Probably was following whatever the policy was when Gumbo was open-sourced in 2013.  I have no objection to renaming it.)

**Comment by Falven** [comment]
@nostrademons silly conventions :)
thanks

**Comment by yexf** [comment]
sorry,I will delete the repository




yexf_fyf

From: Francisco Aguilera
Date: 2016-03-08 14:00
To: google/gumbo-parser
Subject: [gumbo-parser] licensing? (#364)
There is no licensing information anywhere that I can see. Could this information be provided or made more apparent? Usually repositories provide a LICENSE.txt in their top level directory with relevant information.

**Comment by z3ntu** [comment]
Can be closed.
