### ISSUE TITLE
Xcode warning for strcpy

### ISSUE THREAD

**Issue by Sopan** [google/gumbo-parser#366]
After building and analyzing gumbo parser in Xcode, it gives a warning for using "strcpy" in `util.c` since it doesn't provide bounding for memory buffer.

Should the below code be changed from

`char* buffer = gumbo_parser_allocate(parser, strlen(str) + 1);
strcpy(buffer, str);`

to 

`char* buffer = gumbo_parser_allocate(parser, strlen(str) + 1);
strlcpy(buffer, str, sizeof(buffer));`

**Comment by kevinhendricks** [comment]
AFAIK, strlcopy is not POSIX and not available on all unix systems.  It is mainly a BSD thing.  

The first line will allocate enough bytes to store whatever str has in it (plus 1 for the terminating null), so that the strcpy that comes next can not overflow. 

If memory is low, and the return value from the buffer allocation is not tested, then you could have an issue but both strlcpy and strcpy would fail.  

Also sizeof(buffer) is really the size of a char * in this case since buffer is not an array or structure so that makes no sense to me.

**Comment by Sopan** [comment]
I understand what you are saying, the code suggested is not the right way. I should just suppress the warning because memory bound condition is already handled and it's just not pointing out any legit issue.
